server.port=8080

# ==============================================================================
# 💾 CONFIGURACIÓN REACTIVA BASE DE DATOS (INYECCIÓN DINÁMICA DE ENTORNO)
# ==============================================================================
# Si la variable global no existe en el sistema, cae automáticamente por defecto en tu Pooler de Supabase
spring.r2dbc.url=${SPRING_R2DBC_URL:r2dbc:postgresql://aws-1-us-west-1.pooler.supabase.com:5432/postgres?sslMode=require}
spring.r2dbc.username=${SPRING_DATABASE_USERNAME:postgres.rslxsrsrquardptnjvgl}
spring.r2dbc.password=${SPRING_DATABASE_PASSWORD:JOSEand6394#gge}

spring.sql.init.mode=never
spring.main.web-application-type=reactive

# ==============================================================================
# ☁️ MICROSERVICIOS Y INTEGRACIÓN SUPABASE STORAGE
# ==============================================================================
supabase.url=${SUPABASE_URL:https://rslxsrsrquardptnjvgl.supabase.co}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY:TU_SERVICE_ROLE_KEY}

# Buckets maestros del sistema multimedia
supabase.bucket.originales=original-images
supabase.bucket.processed=processed-images

# 🔌 Enlace de red interna hacia el contenedor Flask de PyCUDA
# Dentro de la red de Docker, localhost no funciona; se usa el alias del servicio
# 🔌 Enlace de red interna hacia el contenedor Flask de PyCUDA
flask.server.url=${FLASK_SERVER_URL:http://flask_service:5000}