server.port=8080

# ==============================================================================
# SUPABASE R2DBC - SESSION POOLER IPv4
# ==============================================================================

spring.r2dbc.url=r2dbc:postgresql://aws-1-us-west-1.pooler.supabase.com:5432/postgres?sslMode=require

spring.r2dbc.username=postgres.rslxsrsrquardptnjvgl

spring.r2dbc.password=JOSEand6394#gge

spring.sql.init.mode=never
spring.main.web-application-type=reactive

# ==============================================================================
# SUPABASE STORAGE
# ==============================================================================

supabase.url=https://rslxsrsrquardptnjvgl.supabase.co

supabase.service-role-key=TU_SERVICE_ROLE_KEY

supabase.bucket.originales=original-images
supabase.bucket.processed=processed-images